// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVtZ97kIqt1cH7FT-CR-0_-bZJwFwYNww',
    appId: '1:238655575119:web:7db09047d65795d942063a',
    messagingSenderId: '238655575119',
    projectId: 'capstone-c8066',
    authDomain: 'capstone-c8066.firebaseapp.com',
    storageBucket: 'capstone-c8066.firebasestorage.app',
    measurementId: 'G-9D14NE41HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxGJ8o6bNnCfNtLvlrjYsQ5vpHjDoaEes',
    appId: '1:238655575119:android:2958d6e46fb1a24142063a',
    messagingSenderId: '238655575119',
    projectId: 'capstone-c8066',
    storageBucket: 'capstone-c8066.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXe9Pr6p3SIxcFUORG9Ei1lCS0KENlOI4',
    appId: '1:238655575119:ios:f32cb7d3554da44f42063a',
    messagingSenderId: '238655575119',
    projectId: 'capstone-c8066',
    storageBucket: 'capstone-c8066.firebasestorage.app',
    iosClientId:
        '238655575119-q823ocbdoerjtb6o9ri96rc4l0gjnl96.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXe9Pr6p3SIxcFUORG9Ei1lCS0KENlOI4',
    appId: '1:238655575119:ios:f32cb7d3554da44f42063a',
    messagingSenderId: '238655575119',
    projectId: 'capstone-c8066',
    storageBucket: 'capstone-c8066.firebasestorage.app',
    iosClientId:
        '238655575119-q823ocbdoerjtb6o9ri96rc4l0gjnl96.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVtZ97kIqt1cH7FT-CR-0_-bZJwFwYNww',
    appId: '1:238655575119:web:358fc3688c4aaf2c42063a',
    messagingSenderId: '238655575119',
    projectId: 'capstone-c8066',
    authDomain: 'capstone-c8066.firebaseapp.com',
    storageBucket: 'capstone-c8066.firebasestorage.app',
    measurementId: 'G-ZWNJH9G9VW',
  );
}
